# Generated by Django 5.2.8 on 2025-11-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
