# Generated by Django 5.2.8 on 2025-11-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_target_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='target_date',
        ),
    ]
